"""
Caveman plugin for AstrBot.

Makes the LLM respond with extreme brevity, cutting ~65 % of output tokens
while keeping full technical accuracy.  Inspired by JuliusBrussee/caveman.

Architecture overview
---------------------
* ``CavemanPlugin`` — the AstrBot star plugin class.
* Command group ``/caveman`` with subcommands (help, status, on, off,
  lite, full, ultra, wenyan, wenyan-lite, wenyan-ultra).
* ``inject_caveman`` — fires on every LLM request, prepending a caveman
  instruction to ``system_prompt`` when the session is active.
* Session state is kept in memory (dict: ``session_id → {enabled, level}``).
* All user-facing strings go through the i18n layer so the plugin speaks the
  same language as the rest of the bot.

Why keep CAVEMAN_PROMPTS in English?
------------------------------------
The prompt strings are **system instructions** fed directly to the LLM.
English style prompts perform more reliably across models; translating them
into the UI language would degrade the compression quality.  Only the
*human* messages (help text, status replies, errors) are localized.
"""

from astrbot.api import star
from astrbot.api.event import AstrMessageEvent, MessageEventResult, filter
from astrbot.api.event.filter import PermissionType, permission_type
from astrbot.core.provider.entities import ProviderRequest
from .core.i18n_backend import init, t


# ---------------------------------------------------------------------------
# System-level prompt instructions.
# Each key is a compression level.  The text is injected verbatim into the
# system prompt when that level is active for the current session.
# ---------------------------------------------------------------------------
CAVEMAN_PROMPTS = {
    "lite": (
        "Be concise. Remove filler words and polite phrases. "
        "Keep professional tone but get straight to the point. "
        "No throat-clearing, no 'I would recommend', no 'Sure!'."
    ),
    "full": (
        "Talk like caveman. Maximum brevity. "
        "Drop articles, filler, and pleasantries. "
        "Use fragments, arrows, and abbreviations. "
        "Get straight to technical answer. "
        "No 'I think', 'You should', 'Let me explain'. "
        "Just facts and code."
    ),
    "ultra": (
        "Maximum compression. Telegraphic style. "
        "Single words where possible. Abbreviate everything. "
        "Omit all grammar. Code blocks only when needed. "
        "Raw technical data. No sentences."
    ),
    "wenyan-lite": (
        "Respond in terse classical Chinese literary style with modern technical terms. "
        "Maximum compression. Grammar intact, filler gone."
    ),
    "wenyan": (
        "Respond in full 文言文 (classical Chinese). "
        "Maximum classical terseness. Technical accuracy preserved."
    ),
    "wenyan-ultra": (
        "Respond in extreme 文言文. Ancient scholar style. "
        "Minimum characters. Maximum meaning."
    ),
}


class CavemanPlugin(star.Star):
    """
    AstrBot plugin that compresses LLM answers on a per-session basis.

    Attributes:
        _states: Mapping ``session_id → {"enabled": bool, "level": str}``.
            Volatile — reset when AstrBot restarts.
    """

    def __init__(self, context: star.Context, config: dict = None) -> None:
        """
        Initialise the plugin and load translations.

        Accepts the AstrBot plugin *config* dict (populated from the WebUI
        form generated by ``_conf_schema.json``).  Falls back to empty dict
        when running on older AstrBot versions that do not pass the second
        argument.

        The ``language`` setting drives i18n.  ``auto`` means "follow AstrBot's
        global ``bot_language``" (best-effort); any explicit code forces that
        locale regardless of the global setting.
        """
        super().__init__(context)
        config = config or {}

        # session_id → {"enabled": bool, "level": str}
        # Kept in memory only; users must re-enable after a bot restart.
        self._states: dict[str, dict] = {}

        # Store config for runtime access (default_level, auto_enable, etc.)
        self._config: dict = config

        # -------------------------------------------------------------------
        # Resolve the i18n language.
        #   1. If user explicitly set a language in plugin config → use it.
        #   2. Otherwise try to read AstrBot's global bot_language.
        #   3. Ultimate fallback → en-US.
        # -------------------------------------------------------------------
        lang_override: str = config.get("language", "auto")
        if lang_override and lang_override != "auto":
            lang: str = lang_override
        else:
            try:
                cfg = getattr(context, "config", None)
                lang = cfg.get("bot_language", "en-US") if cfg else "en-US"
            except Exception:
                lang = "en-US"
        init(lang)

        # -------------------------------------------------------------------
        # If auto_enable is on, every newly seen session starts in caveman
        # mode automatically.  We do NOT touch existing sessions here.
        # -------------------------------------------------------------------
        self._auto_enable: bool = bool(config.get("auto_enable", False))
        self._default_level: str = config.get("default_level", "full")

    # -----------------------------------------------------------------------
    # State helpers
    # -----------------------------------------------------------------------

    def _get_state(self, session_id: str) -> dict:
        """
        Return the caveman state for *session_id*.

        If this is the first time the session is seen we apply the plugin
        configuration defaults:
            * ``auto_enable`` → start with caveman ON?
            * ``default_level`` → which compression level to use?
        """
        if session_id not in self._states:
            self._states[session_id] = {
                "enabled": self._auto_enable,
                "level": self._default_level,
            }
        return self._states[session_id]

    def _set_state(self, session_id: str, enabled: bool, level: str = "full") -> None:
        """Persist a new caveman state for *session_id*."""
        self._states[session_id] = {"enabled": enabled, "level": level}

    # -----------------------------------------------------------------------
    # Help builder (localised)
    # -----------------------------------------------------------------------

    def _build_help(self) -> str:
        """
        Assemble the ``/caveman`` help text from translation keys.

        Dynamically pulls command names, descriptions and mode labels from
        the active locale so the help message is never out of sync with the
        language setting.
        """
        prefix: str = getattr(self.context, "prefix", "/")
        doc: str = t("meta.doc")
        percentage: str = "65"  # documented average token reduction

        lines = [
            t("help.title"),
            t("help.usage", prefix=prefix),
            t("help.introduce", percentage=percentage),
            t("help.docText", doc=doc),
            "",
            "## " + t("help.commands_title"),
        ]

        # Render the four primary commands with their localised descriptions.
        for cmd_key, cmd_desc in [
            ("on", t("help.commands.on")),
            ("off", t("help.commands.off")),
            ("status", t("help.commands.status")),
            ("help", t("help.commands.help")),
        ]:
            lines.append(f"/caveman {cmd_key:<12} — {cmd_desc}")

        lines.append("")
        lines.append("## " + t("help.modes_title"))

        # Render the four most common compression levels.
        for mode_key, mode_desc in [
            ("lite", t("help.modes.lite")),
            ("full", t("help.modes.full")),
            ("ultra", t("help.modes.ultra")),
            ("wenyan", t("help.modes.wenyan")),
        ]:
            lines.append(f"• {mode_key:<6} — {mode_desc}")

        lines.append("")
        lines.append(t("help.level_stick"))
        return "\n".join(lines)

    # =======================================================================
    # Command group /caveman
    # =======================================================================

    @filter.command_group("caveman")
    def caveman(self):
        """LLM output compression command group /caveman"""
        pass

    @permission_type(PermissionType.ADMIN)
    @caveman.command("help")
    async def cmd_help(self, event: AstrMessageEvent) -> None:
        """[Admin] Show caveman help information"""
        event.set_result(MessageEventResult().message(self._build_help()))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("status")
    async def cmd_status(self, event: AstrMessageEvent) -> None:
        """[Admin] Show current caveman mode and compression level"""
        session_id: str = event.session_id
        state: dict = self._get_state(session_id)
        status = t("messages.caveman_on_emoji") + (" ON" if state["enabled"] else " OFF")
        level = state["level"]
        event.set_result(
            MessageEventResult().message(
                f"{t('messages.caveman_prefix')}: {status}\n"
                f"{t('messages.level')}: {level}"
            )
        )

    @permission_type(PermissionType.ADMIN)
    @caveman.command("on")
    async def cmd_on(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable caveman mode (default: full compression)"""
        self._set_state(event.session_id, True, "full")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="FULL")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("off")
    async def cmd_off(self, event: AstrMessageEvent) -> None:
        """[Admin] Disable caveman mode, return to normal"""
        self._set_state(event.session_id, False)
        event.set_result(MessageEventResult().message(t("messages.mode_off")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("lite")
    async def cmd_lite(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable lite compression — professional, no fluff"""
        self._set_state(event.session_id, True, "lite")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="LITE")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("full")
    async def cmd_full(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable full caveman mode — drop articles, fragments"""
        self._set_state(event.session_id, True, "full")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="FULL")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("ultra")
    async def cmd_ultra(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable ultra compression — telegraphic, maximum compression"""
        self._set_state(event.session_id, True, "ultra")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="ULTRA")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("wenyan")
    async def cmd_wenyan(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable wenyan mode — classical Chinese terseness"""
        self._set_state(event.session_id, True, "wenyan")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="WENYAN")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("wenyan-lite")
    async def cmd_wenyan_lite(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable wenyan-lite mode — semi-classical Chinese"""
        self._set_state(event.session_id, True, "wenyan-lite")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="WENYAN-LITE")))

    @permission_type(PermissionType.ADMIN)
    @caveman.command("wenyan-ultra")
    async def cmd_wenyan_ultra(self, event: AstrMessageEvent) -> None:
        """[Admin] Enable wenyan-ultra mode — extreme classical Chinese"""
        self._set_state(event.session_id, True, "wenyan-ultra")
        event.set_result(MessageEventResult().message(t("messages.mode_on", level="WENYAN-ULTRA")))

    # =======================================================================
    # LLM-request interceptor
    # =======================================================================

    @filter.on_llm_request()
    async def inject_caveman(self, event: AstrMessageEvent, req: ProviderRequest) -> None:
        """
        Inject the caveman instruction into the system prompt before the LLM sees it.

        This hook is invoked automatically for **every** outgoing LLM request.
        When the current session has caveman enabled we prepend the selected
        compression prompt to ``req.system_prompt``.  A sentinel marker
        ``[CAVEMAN_MODE_ACTIVE]`` guards against double-injection in case
        the same request passes through the pipeline more than once.

        :param event: The AstrBot event carrying session identity.
        :param req:   The ProviderRequest object whose ``system_prompt``
                      will be modified in-place.
        """
        state: dict = self._get_state(event.session_id)
        if not state["enabled"]:
            return

        level: str = state["level"]
        instruction: str = CAVEMAN_PROMPTS.get(level, CAVEMAN_PROMPTS["full"])

        # Sentinel check — prevents duplicate injection on retries or
        # chained middleware.
        marker: str = "[CAVEMAN_MODE_ACTIVE]"
        if marker in (req.system_prompt or ""):
            return

        # Prepend the caveman block so the instruction sits at the very top
        # of the system prompt, giving it maximum influence over the model.
        caveman_block: str = f"{marker}\n{instruction}\n{marker}\n\n"
        req.system_prompt = caveman_block + (req.system_prompt or "")
